// 暫用假資料，待接 Google Sheets API 後替換

export const MOCK_LAWYERS = [
  { id: 'A', activeCases: 8,  plannedCloseThisMonth: 4, closedThisMonth: 3, avgCycleDays: 42, upcomingDeadlines: 2, billingHours: 98,  billingHoursLastMonth: 88,  overdue: { expired: 1, warning: 2 }, caseTypes: [{ type: '民事訴訟', count: 3, avgDays: 118 }, { type: '家事案件', count: 2, avgDays: 75 }, { type: '財富傳承', count: 2, avgDays: 52 }, { type: '行政訴訟', count: 1, avgDays: 188 }] },
  { id: 'B', activeCases: 6,  plannedCloseThisMonth: 3, closedThisMonth: 2, avgCycleDays: 38, upcomingDeadlines: 1, billingHours: 110, billingHoursLastMonth: 120, overdue: { expired: 2, warning: 1 }, caseTypes: [{ type: '智慧財產', count: 3, avgDays: 162 }, { type: '商事相關', count: 2, avgDays: 68 }, { type: '勞資糾紛', count: 1, avgDays: 104 }] },
  { id: 'C', activeCases: 5,  plannedCloseThisMonth: 5, closedThisMonth: 4, avgCycleDays: 30, upcomingDeadlines: 0, billingHours: 85,  billingHoursLastMonth: 80,  overdue: { expired: 0, warning: 1 }, caseTypes: [{ type: '商事相關', count: 3, avgDays: 65 }, { type: '民事訴訟', count: 2, avgDays: 110 }] },
  { id: 'D', activeCases: 7,  plannedCloseThisMonth: 2, closedThisMonth: 1, avgCycleDays: 55, upcomingDeadlines: 1, billingHours: 105, billingHoursLastMonth: 98,  overdue: { expired: 1, warning: 2 }, caseTypes: [{ type: '刑事訴訟', count: 4, avgDays: 225 }, { type: '民事訴訟', count: 2, avgDays: 132 }, { type: '行政訴訟', count: 1, avgDays: 201 }] },
  { id: 'E', activeCases: 4,  plannedCloseThisMonth: 3, closedThisMonth: 2, avgCycleDays: 28, upcomingDeadlines: 0, billingHours: 72,  billingHoursLastMonth: 75,  overdue: { expired: 0, warning: 0 }, caseTypes: [{ type: '家事案件', count: 2, avgDays: 88 }, { type: '財富傳承', count: 2, avgDays: 42 }] },
  { id: 'F', activeCases: 6,  plannedCloseThisMonth: 3, closedThisMonth: 2, avgCycleDays: 50, upcomingDeadlines: 3, billingHours: 125, billingHoursLastMonth: 115, overdue: { expired: 1, warning: 3 }, caseTypes: [{ type: '勞資糾紛', count: 3, avgDays: 98 }, { type: '民事訴訟', count: 2, avgDays: 128 }, { type: '行政訴訟', count: 1, avgDays: 205 }] },
  { id: 'G', activeCases: 3,  plannedCloseThisMonth: 2, closedThisMonth: 1, avgCycleDays: 35, upcomingDeadlines: 0, billingHours: 58,  billingHoursLastMonth: 62,  overdue: { expired: 0, warning: 0 }, caseTypes: [{ type: '智慧財產', count: 2, avgDays: 148 }, { type: '商事相關', count: 1, avgDays: 78 }] },
  { id: 'H', activeCases: 5,  plannedCloseThisMonth: 4, closedThisMonth: 3, avgCycleDays: 44, upcomingDeadlines: 1, billingHours: 90,  billingHoursLastMonth: 85,  overdue: { expired: 0, warning: 1 }, caseTypes: [{ type: '財富傳承', count: 3, avgDays: 45 }, { type: '家事案件', count: 2, avgDays: 84 }] },
  { id: 'I', activeCases: 4,  plannedCloseThisMonth: 3, closedThisMonth: 2, avgCycleDays: 32, upcomingDeadlines: 0, billingHours: 78,  billingHoursLastMonth: 78,  overdue: { expired: 0, warning: 0 }, caseTypes: [{ type: '民事訴訟', count: 2, avgDays: 120 }, { type: '商事相關', count: 2, avgDays: 74 }] },
  { id: 'J', activeCases: 6,  plannedCloseThisMonth: 3, closedThisMonth: 2, avgCycleDays: 48, upcomingDeadlines: 2, billingHours: 108, billingHoursLastMonth: 100, overdue: { expired: 1, warning: 2 }, caseTypes: [{ type: '刑事訴訟', count: 3, avgDays: 198 }, { type: '行政訴訟', count: 2, avgDays: 192 }, { type: '勞資糾紛', count: 1, avgDays: 102 }] },
  { id: 'K', activeCases: 5,  plannedCloseThisMonth: 4, closedThisMonth: 3, avgCycleDays: 36, upcomingDeadlines: 1, billingHours: 88,  billingHoursLastMonth: 92,  overdue: { expired: 0, warning: 1 }, caseTypes: [{ type: '商事相關', count: 3, avgDays: 70 }, { type: '智慧財產', count: 2, avgDays: 158 }] },
  { id: 'L', activeCases: 3,  plannedCloseThisMonth: 2, closedThisMonth: 1, avgCycleDays: 29, upcomingDeadlines: 0, billingHours: 55,  billingHoursLastMonth: 50,  overdue: { expired: 0, warning: 0 }, caseTypes: [{ type: '家事案件', count: 2, avgDays: 78 }, { type: '民事訴訟', count: 1, avgDays: 115 }] },
]

export const MOCK_ACTIVE_CASES = [
  { type: '民事訴訟', count: 12 },
  { type: '刑事訴訟', count: 5 },
  { type: '家事案件', count: 8 },
  { type: '財富傳承', count: 6 },
  { type: '行政訴訟', count: 3 },
  { type: '勞資糾紛', count: 7 },
  { type: '智慧財產', count: 4 },
  { type: '商事相關', count: 10 },
]

export const MOCK_RETAINED_CASES = [
  { type: '民事訴訟', count: 7, date: '2026-03-10' },
  { type: '刑事訴訟', count: 2, date: '2026-04-01' },
  { type: '家事案件', count: 5, date: '2026-02-20' },
  { type: '財富傳承', count: 4, date: '2026-03-25' },
  { type: '行政訴訟', count: 1, date: '2026-05-01' },
  { type: '勞資糾紛', count: 3, date: '2026-01-30' },
  { type: '智慧財產', count: 2, date: '2026-04-15' },
  { type: '商事相關', count: 8, date: '2026-03-05' },
]

export const MOCK_CONSULTATION_CASES = [
  { type: '民事訴訟', count: 9, date: '2026-03-05' },
  { type: '刑事訴訟', count: 3, date: '2026-04-10' },
  { type: '家事案件', count: 6, date: '2026-02-15' },
  { type: '財富傳承', count: 5, date: '2026-03-30' },
  { type: '行政訴訟', count: 2, date: '2026-05-05' },
  { type: '勞資糾紛', count: 4, date: '2026-01-25' },
  { type: '智慧財產', count: 3, date: '2026-04-20' },
  { type: '商事相關', count: 6, date: '2026-03-15' },
]

export const MOCK_KPI = {
  // 本月
  plannedCloseThisMonth: 11,
  closedThisMonth: 9,
  conversionRate: 68,
  consultationHours: 48,
  // 上月底結算（比較基準）
  plannedCloseLastMonth: 9,
  closedLastMonth: 7,
  conversionRateLastMonth: 63,
  // 帳務（無上月比較基準，暫用靜態趨勢）
  overdueInvoices: 2,
  upcomingDeadlines: 3,
  uninvoiced: 5,
  uninvoicedTrend: { label: '-2 件', up: false, positive: true },
  uninvoicedAmount: 285000,
  invoicedUnpaid: 3,
  invoicedUnpaidTrend: { label: '-1 件', up: false, positive: true },
  invoicedUnpaidAmount: 142000,
}

export const CASE_STATUSES = [
  { key: 'appointment', label: '預約諮詢', color: '#94A3B8', bg: '#F8FAFC' },
  { key: 'meeting',     label: '進行會晤', color: '#8B5CF6', bg: '#F5F3FF' },
  { key: 'quote',       label: '報價',     color: '#0D9488', bg: '#F0FDFA' },
  { key: 'signing',     label: '簽約',     color: '#F97316', bg: '#FFF7ED' },
  { key: 'active',      label: '進行中',   color: '#1E3480', bg: '#EEF2FF' },
  { key: 'closed',      label: '結案',     color: '#22C55E', bg: '#F0FDF4' },
]

export const MOCK_CASES = [
  { id: 'C-2026-051', parties: '王○○',                   cause: '侵權行為',           relief: '請求損害賠償',             type: '民事訴訟', status: 'appointment', lawyer: 'A', nextDeadline: null,         expectedCloseDate: null         },
  { id: 'C-2026-050', parties: '○○餐飲集團',              cause: '不當解雇爭議',         relief: '確認僱傭關係存在',           type: '勞資糾紛', status: 'meeting',     lawyer: 'B', nextDeadline: null,         expectedCloseDate: null         },
  { id: 'C-2026-049', parties: '林○○',                   cause: '遺囑信託',            relief: '信託規劃諮詢',              type: '財富傳承', status: 'quote',       lawyer: 'E', nextDeadline: null,         expectedCloseDate: null         },
  { id: 'C-2026-033', parties: '○○科技股份有限公司',       cause: '商標侵權',            relief: '損害賠償及排除侵害',          type: '智慧財產', status: 'signing',     lawyer: 'B', nextDeadline: '2026-05-30', expectedCloseDate: '2026-08-15' },
  { id: 'C-2026-048', parties: '○○科技股份有限公司',       cause: '軟體授權合約爭議',      relief: '請求履行合約義務',            type: '智慧財產', status: 'active',    lawyer: 'B', nextDeadline: '2026-06-10', expectedCloseDate: '2026-09-30' },
  { id: 'C-2026-047', parties: '張○○',                   cause: '離婚',               relief: '財產分配',                  type: '家事案件', status: 'active',    lawyer: 'E', nextDeadline: '2026-06-15', expectedCloseDate: '2026-10-15' },
  { id: 'C-2026-046', parties: '○○建設股份有限公司',       cause: '工程承攬契約爭議',      relief: '請求給付工程款',             type: '商事相關', status: 'active',    lawyer: 'C', nextDeadline: '2026-06-08', expectedCloseDate: '2026-08-30' },
  { id: 'C-2026-041', parties: '王○○',                   cause: '借貸契約爭議',         relief: '請求給付借款',               type: '民事訴訟', status: 'active',      lawyer: 'A', nextDeadline: '2026-05-28', expectedCloseDate: '2026-06-15', subCases: ['C-2026-041-A'], pendingReview: false },
  { id: 'C-2026-040', parties: '○○製藥股份有限公司',       cause: '專利侵權',            relief: '損害賠償及停止侵害',          type: '智慧財產', status: 'active',      lawyer: 'B', nextDeadline: '2026-06-02', expectedCloseDate: '2026-05-20', subCases: ['C-2026-040-A'], pendingReview: false },
  { id: 'C-2026-039', parties: '劉○○（被告）',            cause: '詐欺罪嫌',            relief: '無罪辯護',                  type: '刑事訴訟', status: 'active',      lawyer: 'D', nextDeadline: '2026-06-05', expectedCloseDate: '2026-05-10', subCases: ['C-2026-039-A'], pendingReview: false },
  { id: 'C-2026-038', parties: '○○物流股份有限公司',       cause: '行政裁罰處分',         relief: '撤銷原處分',                type: '行政訴訟', status: 'active',      lawyer: 'F', nextDeadline: '2026-06-01', expectedCloseDate: '2026-06-10' },
  { id: 'C-2026-037', parties: '陳○○',                   cause: '繼承爭議',            relief: '遺產分割',                  type: '財富傳承', status: 'active',      lawyer: 'H', nextDeadline: '2026-06-12', expectedCloseDate: '2026-08-01' },
  { id: 'C-2026-036', parties: '○○電商股份有限公司',       cause: '消費者保護爭議',        relief: '集體損害賠償',               type: '商事相關', status: 'active',      lawyer: 'C', nextDeadline: '2026-06-20', expectedCloseDate: '2026-09-01' },
  { id: 'C-2026-030', parties: '黃○○',                   cause: '勞動契約終止爭議',      relief: '確認僱傭關係存在',            type: '勞資糾紛', status: 'active',      lawyer: 'F', nextDeadline: '2026-06-03', expectedCloseDate: '2026-06-20' },
  { id: 'C-2026-027', parties: '張○○',                   cause: '繼承爭議',            relief: '遺產分割',                  type: '財富傳承', status: 'active',      lawyer: 'A', nextDeadline: '2026-06-01', expectedCloseDate: '2026-07-01' },
  { id: 'C-2026-020', parties: '○○金融股份有限公司',       cause: '借貸契約履行爭議',      relief: '請求清償借款',               type: '商事相關', status: 'closed',      lawyer: 'K', nextDeadline: null,         expectedCloseDate: null,         subCases: ['C-2026-020-A'], pendingReview: false },
  { id: 'C-2026-018', parties: '吳○○',                   cause: '家庭暴力',            relief: '聲請保護令',                type: '家事案件', status: 'closed',      lawyer: 'E', nextDeadline: null,         expectedCloseDate: null         },
  { id: 'C-2026-015', parties: '林○○',                   cause: '勞資爭議',            relief: '仲裁請求',                  type: '勞資糾紛', status: 'closed',      lawyer: 'F', nextDeadline: null,         expectedCloseDate: null         },

  // --- 子案：上訴 ---
  { id: 'C-2026-041-A', parties: '王○○',                 cause: '借貸契約爭議',         relief: '請求給付借款',         type: '民事訴訟', status: 'signing',  lawyer: 'A', nextDeadline: '2026-06-15', expectedCloseDate: '2026-10-30', parentCaseId: 'C-2026-041', subType: 'appeal',      instanceLevel: '二審' },
  { id: 'C-2026-040-A', parties: '○○製藥股份有限公司',     cause: '專利侵權',            relief: '損害賠償及停止侵害',    type: '智慧財產', status: 'active',   lawyer: 'B', nextDeadline: '2026-06-20', expectedCloseDate: '2026-11-15', parentCaseId: 'C-2026-040', subType: 'appeal',      instanceLevel: '二審' },
  { id: 'C-2026-039-A', parties: '劉○○（被告）',          cause: '詐欺罪嫌',            relief: '無罪辯護',             type: '刑事訴訟', status: 'quote',    lawyer: 'D', nextDeadline: null,         expectedCloseDate: null,         parentCaseId: 'C-2026-039', subType: 'appeal',      instanceLevel: '二審' },

  // --- 子案：強制執行 ---
  { id: 'C-2026-020-A', parties: '○○金融股份有限公司',     cause: '借貸契約履行',         relief: '強制執行',                  type: '商事相關', status: 'active', lawyer: 'K', nextDeadline: '2026-06-10', expectedCloseDate: '2026-08-01', parentCaseId: 'C-2026-020', subType: 'enforcement', instanceLevel: null },
]

export const CONTACT_TYPES = [
  '電話會議',
  '視訊會議',
  '到所面談',
  '文件簽署',
  '進度更新',
  '開庭',
  '客戶不滿意處理',
  '預約諮詢安排',
]

export const DEADLINE_CATEGORIES = {
  STATUTORY:   { label: '法定期間', color: 'bg-red-50 text-red-600' },
  HEARING:     { label: '庭審期日', color: 'bg-blue-50 text-blue-600' },
  NON_HEARING: { label: '非庭審期日', color: 'bg-indigo-50 text-indigo-600' },
  FILING:      { label: '書狀截止', color: 'bg-purple-50 text-purple-600' },
  RETAINER:    { label: '委任到期', color: 'bg-orange-50 text-orange-600' },
  INVOICE:     { label: '帳單付款', color: 'bg-yellow-50 text-yellow-700' },
  FOLLOWUP:    { label: '客戶追蹤', color: 'bg-teal-50 text-teal-600' },
}

export const MOCK_CLIENT_HEALTH = [
  {
    id: 'ch-1',
    client: '○○科技',
    caseNo: 'C-2026-048',
    parties: '○○科技股份有限公司',
    cause: '軟體授權合約爭議',
    relief: '請求履行合約義務',
    caseType: '智慧財產',
    status: 'active',
    lawyer: 'B',
    lastContactDate: '2026-05-23',
    contacts: [
      { id: 1, date: '2026-05-23', type: '電話會議', lawyer: 'B', note: '確認軟體授權訴訟進度，客戶表示認可目前策略' },
      { id: 2, date: '2026-05-15', type: '進度更新', lawyer: 'B', note: '收到對方答辯書，已向客戶說明影響範圍' },
      { id: 3, date: '2026-05-05', type: '到所面談', lawyer: 'B', note: '討論訴訟策略，確認下一步行動方案' },
    ],
    followUps: [
      { id: 1, date: '2026-06-10', task: '開庭前文件確認', done: false, category: 'HEARING' },
      { id: 2, date: '2026-06-20', task: '寄送月度進度報告', done: false, category: 'FOLLOWUP' },
    ],
    driveLinks: [
      { id: 1, name: '委任合約書', url: '#' },
      { id: 2, name: '訴訟策略簡報', url: '#' },
    ],
  },
  {
    id: 'ch-2',
    client: '王○○',
    caseNo: 'C-2026-041',
    parties: '王○○',
    cause: '借貸契約爭議',
    relief: '請求給付借款',
    caseType: '民事訴訟',
    status: 'active',
    lawyer: 'A',
    lastContactDate: '2026-05-22',
    contacts: [
      { id: 1, date: '2026-05-22', type: '預約諮詢安排', lawyer: 'A', note: '安排 06/05 到所面談，確認開庭後疑問與下一步策略' },
      { id: 2, date: '2026-05-18', type: '視訊會議', lawyer: 'A', note: '說明開庭結果，客戶有疑問需後續補充說明' },
      { id: 3, date: '2026-05-08', type: '開庭', lawyer: 'A', note: '第一次言詞辯論庭，程序順利進行' },
    ],
    followUps: [
      { id: 1, date: '2026-05-28', task: '書狀送達確認', done: false, category: 'FILING' },
      { id: 2, date: '2026-06-01', task: '法律意見書寄送', done: true, category: 'FILING' },
    ],
    driveLinks: [
      { id: 1, name: '起訴狀', url: '#' },
      { id: 2, name: '開庭筆錄', url: '#' },
    ],
  },
  {
    id: 'ch-3',
    client: '○○物流',
    caseNo: 'C-2026-038',
    parties: '○○物流股份有限公司',
    cause: '行政裁罰處分',
    relief: '撤銷原處分',
    caseType: '行政訴訟',
    status: 'active',
    lawyer: 'F',
    lastContactDate: '2026-05-10',
    contacts: [
      { id: 1, date: '2026-05-10', type: '客戶不滿意處理', lawyer: 'F', note: '客戶來電表達對進度遲緩不滿，已安撫並承諾每週主動更新進度' },
      { id: 2, date: '2026-05-05', type: '電話會議', lawyer: 'F', note: '客戶對行政訴訟進度感到焦慮，需加強溝通頻率' },
      { id: 3, date: '2026-04-25', type: '到所面談', lawyer: 'F', note: '討論行政裁罰撤銷策略與勝訴機率評估' },
    ],
    followUps: [
      { id: 1, date: '2026-06-01', task: '行政訴訟答辯狀提交', done: false, category: 'FILING' },
      { id: 2, date: '2026-05-30', task: '主動聯繫客戶更新進度', done: false, category: 'FOLLOWUP' },
    ],
    driveLinks: [
      { id: 1, name: '行政裁罰書', url: '#' },
    ],
  },
  {
    id: 'ch-4',
    client: '張○○',
    caseNo: 'C-2026-047',
    parties: '張○○',
    cause: '離婚',
    relief: '財產分配',
    caseType: '家事案件',
    status: 'active',
    lawyer: 'E',
    lastContactDate: '2026-05-25',
    contacts: [
      { id: 1, date: '2026-05-25', type: '到所面談', lawyer: 'E', note: '離婚協議草案討論，客戶對進展感到滿意' },
      { id: 2, date: '2026-05-20', type: '文件簽署', lawyer: 'E', note: '財產清冊確認簽署完成' },
      { id: 3, date: '2026-05-12', type: '進度更新', lawyer: 'E', note: '案件進展順利，預計如期結案' },
    ],
    followUps: [
      { id: 1, date: '2026-06-15', task: '協議書最終版確認', done: false, category: 'NON_HEARING' },
    ],
    driveLinks: [
      { id: 1, name: '財產清冊', url: '#' },
      { id: 2, name: '離婚協議草案', url: '#' },
    ],
  },
  {
    id: 'ch-5',
    client: '○○電商',
    caseNo: 'C-2026-036',
    parties: '○○電商股份有限公司',
    cause: '消費者保護爭議',
    relief: '集體損害賠償',
    caseType: '商事相關',
    status: 'active',
    lawyer: 'C',
    lastContactDate: '2026-05-14',
    contacts: [
      { id: 1, date: '2026-05-14', type: '視訊會議', lawyer: 'C', note: '集體訴訟策略說明，確認參與原告名單' },
      { id: 2, date: '2026-05-01', type: '進度更新', lawyer: 'C', note: '收到法院傳票，已通知所有相關原告' },
    ],
    followUps: [
      { id: 1, date: '2026-06-20', task: '原告授權書收集完成', done: false, category: 'FILING' },
      { id: 2, date: '2026-06-05', task: '集體訴訟說明會', done: false, category: 'NON_HEARING' },
    ],
    driveLinks: [],
  },
  {
    id: 'ch-6',
    client: '陳○○',
    caseNo: 'C-2026-037',
    parties: '陳○○',
    cause: '繼承爭議',
    relief: '遺產分割',
    caseType: '財富傳承',
    status: 'active',
    lawyer: 'H',
    lastContactDate: '2026-05-21',
    contacts: [
      { id: 1, date: '2026-05-21', type: '到所面談', lawyer: 'H', note: '遺產分割協議進度說明，家屬意見有分歧需協調' },
      { id: 2, date: '2026-05-13', type: '電話會議', lawyer: 'H', note: '與繼承人甲方確認立場與底線' },
    ],
    followUps: [
      { id: 1, date: '2026-06-12', task: '遺產分割協議草案寄送', done: false, category: 'FILING' },
    ],
    driveLinks: [
      { id: 1, name: '遺囑書', url: '#' },
    ],
  },
  {
    id: 'ch-7',
    client: '王○○',
    caseNo: 'C-2026-051',
    parties: '王○○',
    cause: '侵權行為',
    relief: '請求損害賠償',
    caseType: '民事訴訟',
    status: 'appointment',
    lawyer: 'A',
    lastContactDate: '2026-05-24',
    contacts: [
      { id: 1, date: '2026-05-24', type: '預約諮詢安排', lawyer: 'A', note: '客戶來電詢問損害賠償相關事宜，已安排 06/03 初次諮詢' },
    ],
    followUps: [
      { id: 1, date: '2026-06-03', task: '初次諮詢面談', done: false, category: 'NON_HEARING' },
    ],
    driveLinks: [],
  },
  {
    id: 'ch-8',
    client: '○○餐飲集團',
    caseNo: 'C-2026-050',
    parties: '○○餐飲集團',
    cause: '不當解雇爭議',
    relief: '確認僱傭關係存在',
    caseType: '勞資糾紛',
    status: 'meeting',
    lawyer: 'B',
    lastContactDate: '2026-05-25',
    contacts: [
      { id: 1, date: '2026-05-25', type: '到所面談', lawyer: 'B', note: '員工解雇爭議初步說明，確認案件背景與訴求方向' },
    ],
    followUps: [
      { id: 1, date: '2026-06-05', task: '提供服務報價方案', done: false, category: 'NON_HEARING' },
    ],
    driveLinks: [],
  },
]

export const MOCK_UPCOMING_DEADLINES = [
  { id: 1, caseNo: 'C-2026-041', parties: '王○○',               cause: '借貸契約爭議',   relief: '請求給付借款',         caseType: '民事訴訟', category: 'STATUTORY', date: '2026-05-28', daysLeft: 2, lawyer: 'A 律師' },
  { id: 2, caseNo: 'C-2026-033', parties: '○○科技股份有限公司',   cause: '商標侵權',       relief: '損害賠償及排除侵害',     caseType: '智慧財產', category: 'HEARING',   date: '2026-05-30', daysLeft: 4, lawyer: 'B 律師' },
  { id: 3, caseNo: 'C-2026-027', parties: '張○○',               cause: '繼承爭議',       relief: '遺產分割',             caseType: '財富傳承', category: 'FILING',    date: '2026-06-01', daysLeft: 6, lawyer: 'A 律師' },
  { id: 4, caseNo: 'C-2026-019', parties: '○○建設股份有限公司',   cause: '不動產交易爭議', relief: '請求返還價金',           caseType: '商事相關', category: 'RETAINER',  date: '2026-06-01', daysLeft: 6, lawyer: 'C 律師' },
  { id: 5, caseNo: 'C-2026-015', parties: '林○○',               cause: '勞資爭議',       relief: '仲裁請求',             caseType: '勞資糾紛', category: 'INVOICE',   date: '2026-06-02', daysLeft: 7, lawyer: 'B 律師' },
]

export const MOCK_CYCLE_DAYS_BY_TYPE = [
  { type: '民事訴訟', avgDays: 124 },
  { type: '刑事訴訟', avgDays: 210 },
  { type: '家事案件', avgDays: 82  },
  { type: '財富傳承', avgDays: 48  },
  { type: '行政訴訟', avgDays: 195 },
  { type: '勞資糾紛', avgDays: 96  },
  { type: '智慧財產', avgDays: 156 },
  { type: '商事相關', avgDays: 72  },
]

export const STATUTE_TYPES = ['消滅時效', '取得時效', '追訴時效', '除斥期間', '合約期間']

export const MOCK_STATUTES = [
  // ── 消滅時效 ──────────────────────────────────────────────────────────
  {
    id: 'SOL-001',
    law: '民法第 125 條',
    name: '一般請求權消滅時效',
    type: '消滅時效',
    years: 15,
    days: 5475,
    display: '15 年',
    caseTypes: ['民事訴訟', '商事相關', '財富傳承'],
    note: '債權等一般請求權之基本時效，自請求權可行使時起算',
  },
  {
    id: 'SOL-002',
    law: '民法第 126 條',
    name: '定期給付請求權',
    type: '消滅時效',
    years: 5,
    days: 1825,
    display: '5 年',
    caseTypes: ['民事訴訟', '商事相關', '勞資糾紛'],
    note: '利息、租金、薪資、贍養費等定期給付請求權',
  },
  {
    id: 'SOL-003',
    law: '民法第 127 條',
    name: '商業短期消滅時效',
    type: '消滅時效',
    years: 2,
    days: 730,
    display: '2 年',
    caseTypes: ['商事相關', '勞資糾紛'],
    note: '商人供給商品或產品之代價、餐旅住宿費、技能勞務報酬等',
  },
  {
    id: 'SOL-004',
    law: '民法第 197 條第 1 項',
    name: '侵權行為損害賠償（知悉起算）',
    type: '消滅時效',
    years: 2,
    days: 730,
    display: '2 年',
    caseTypes: ['民事訴訟'],
    note: '自知有損害及賠償義務人時起算；需同時具備兩項知悉要件',
  },
  {
    id: 'SOL-005',
    law: '民法第 197 條第 1 項',
    name: '侵權行為損害賠償（行為起算）',
    type: '消滅時效',
    years: 10,
    days: 3650,
    display: '10 年',
    caseTypes: ['民事訴訟'],
    note: '自侵權行為時起算之絕對消滅時效，不因不知而延長',
  },
  {
    id: 'SOL-006',
    law: '民法第 514 條',
    name: '承攬報酬及費用請求權',
    type: '消滅時效',
    years: 2,
    days: 730,
    display: '2 年',
    caseTypes: ['商事相關'],
    note: '承攬人之報酬及其墊款請求權，自工作交付時起算',
  },
  {
    id: 'SOL-007',
    law: '勞動基準法第 58 條',
    name: '職業災害補償請求權',
    type: '消滅時效',
    years: 2,
    days: 730,
    display: '2 年',
    caseTypes: ['勞資糾紛'],
    note: '勞工職業災害補償請求權，自得受領之日起算',
  },
  {
    id: 'SOL-008',
    law: '勞動基準法第 55 條',
    name: '退休金請求權',
    type: '消滅時效',
    years: 5,
    days: 1825,
    display: '5 年',
    caseTypes: ['勞資糾紛'],
    note: '勞工退休金請求權，自退休之次日起算',
  },
  // ── 取得時效 ──────────────────────────────────────────────────────────
  {
    id: 'ACQ-001',
    law: '民法第 768 條',
    name: '動產所有權取得時效（善意占有）',
    type: '取得時效',
    years: 5,
    days: 1825,
    display: '5 年',
    caseTypes: ['民事訴訟', '商事相關'],
    note: '以所有之意思，善意、和平、公然占有他人動產；無法律上原因者為 10 年',
  },
  {
    id: 'ACQ-002',
    law: '民法第 769 條',
    name: '不動產所有權取得時效（善意占有）',
    type: '取得時效',
    years: 10,
    days: 3650,
    display: '10 年',
    caseTypes: ['民事訴訟', '商事相關'],
    note: '以所有之意思，善意、和平、公然繼續占有他人未登記不動產',
  },
  {
    id: 'ACQ-003',
    law: '民法第 770 條',
    name: '不動產所有權取得時效（惡意或有瑕疵占有）',
    type: '取得時效',
    years: 20,
    days: 7300,
    display: '20 年',
    caseTypes: ['民事訴訟'],
    note: '以所有之意思，和平、公然繼續占有他人未登記不動產，但占有之始為惡意或有瑕疵',
  },
  // ── 追訴時效 ──────────────────────────────────────────────────────────
  {
    id: 'PRO-001',
    law: '刑法第 80 條第 1 項第 1 款',
    name: '追訴時效（死刑或無期徒刑）',
    type: '追訴時效',
    years: 30,
    days: 10950,
    display: '30 年',
    caseTypes: ['刑事訴訟'],
    note: '法定刑為死刑或無期徒刑之罪',
  },
  {
    id: 'PRO-002',
    law: '刑法第 80 條第 1 項第 2 款',
    name: '追訴時效（10 年以上有期徒刑）',
    type: '追訴時效',
    years: 20,
    days: 7300,
    display: '20 年',
    caseTypes: ['刑事訴訟'],
    note: '法定最重本刑為 10 年以上有期徒刑之罪',
  },
  {
    id: 'PRO-003',
    law: '刑法第 80 條第 1 項第 3 款',
    name: '追訴時效（3 年以上未滿 10 年）',
    type: '追訴時效',
    years: 10,
    days: 3650,
    display: '10 年',
    caseTypes: ['刑事訴訟'],
    note: '法定最重本刑為 3 年以上未滿 10 年有期徒刑之罪',
  },
  {
    id: 'PRO-004',
    law: '刑法第 80 條第 1 項第 4 款',
    name: '追訴時效（1 年以上未滿 3 年）',
    type: '追訴時效',
    years: 5,
    days: 1825,
    display: '5 年',
    caseTypes: ['刑事訴訟'],
    note: '法定最重本刑為 1 年以上未滿 3 年有期徒刑之罪',
  },
  {
    id: 'PRO-005',
    law: '刑法第 80 條第 1 項第 5 款',
    name: '追訴時效（1 年未滿或罰金）',
    type: '追訴時效',
    years: 1,
    days: 365,
    display: '1 年',
    caseTypes: ['刑事訴訟'],
    note: '法定最重本刑為 1 年未滿有期徒刑、拘役或罰金之罪',
  },
  // ── 除斥期間 ──────────────────────────────────────────────────────────
  {
    id: 'EXC-001',
    law: '民法第 359 條',
    name: '物之瑕疵解除權或減少價金請求權',
    type: '除斥期間',
    years: null,
    days: 180,
    display: '6 個月',
    caseTypes: ['民事訴訟', '商事相關'],
    note: '自買受人知悉瑕疵時起算；不適用消滅時效中斷規定',
  },
  {
    id: 'EXC-002',
    law: '民法第 365 條',
    name: '物之瑕疵擔保請求（交付後絕對期間）',
    type: '除斥期間',
    years: 5,
    days: 1825,
    display: '5 年',
    caseTypes: ['民事訴訟', '商事相關'],
    note: '自交付後 5 年不行使則消滅，為絕對除斥期間',
  },
  {
    id: 'EXC-003',
    law: '民法第 245-1 條',
    name: '締約上過失損害賠償',
    type: '除斥期間',
    years: null,
    days: 365,
    display: '知悉後 1 年 / 契約成立後 3 年',
    caseTypes: ['民事訴訟', '商事相關'],
    note: '自請求權人知悉損害及賠償義務人時起 1 年；契約成立後 3 年為絕對期間',
  },
  {
    id: 'EXC-004',
    law: '民法第 1146 條',
    name: '繼承回復請求權',
    type: '除斥期間',
    years: 2,
    days: 730,
    display: '知悉後 2 年 / 繼承開始後 10 年',
    caseTypes: ['財富傳承', '民事訴訟'],
    note: '自繼承人知悉其繼承被侵害之時起 2 年；自繼承開始起 10 年為絕對期間',
  },
  {
    id: 'EXC-005',
    law: '家事事件法第 52 條',
    name: '撤銷婚姻請求權',
    type: '除斥期間',
    years: null,
    days: 180,
    display: '6 個月',
    caseTypes: ['家事案件'],
    note: '自撤銷原因消滅後 6 個月內行使；逾期不得再主張',
  },
  // ── 合約期間 ──────────────────────────────────────────────────────────
  {
    id: 'CON-001',
    law: '依雙方合意',
    name: '常年法律顧問合約期間',
    type: '合約期間',
    years: 1,
    days: 365,
    display: '1 年',
    caseTypes: ['常年法務'],
    note: '本所標準常年顧問合約效期為 1 年，屆期前 30 日應啟動續約確認；如未於到期日前終止則視為同條件續約',
  },
  {
    id: 'CON-002',
    law: '依雙方合意',
    name: '常年顧問合約終止通知期',
    type: '合約期間',
    years: null,
    days: 30,
    display: '30 日',
    caseTypes: ['常年法務'],
    note: '任一方擬終止合約，應於期滿前至少 30 日以書面通知他方；未依規定通知者須承擔違約責任',
  },
  {
    id: 'CON-003',
    law: '勞動基準法第 9-1 條',
    name: '競業禁止條款最長期間',
    type: '合約期間',
    years: 2,
    days: 730,
    display: '2 年',
    caseTypes: ['勞資糾紛', '商事相關'],
    note: '離職後競業禁止期間不得逾 2 年，逾期部分無效；雇主須給予合理補償，否則約定不生效力',
  },
  {
    id: 'CON-004',
    law: '依合約約定',
    name: '保密協議（NDA）有效期',
    type: '合約期間',
    years: 3,
    days: 1095,
    display: '3 年（常見約定）',
    caseTypes: ['商事相關', '智慧財產', '常年法務'],
    note: '本所常見 NDA 保密期間為 3–5 年；若未約定期間，應依誠信原則判斷合理存續期限',
  },
  {
    id: 'CON-005',
    law: '依合約約定',
    name: '專案法律顧問合約期間',
    type: '合約期間',
    years: null,
    days: 180,
    display: '6 個月（常見約定）',
    caseTypes: ['常年法務', '商事相關'],
    note: '以特定專案為範圍之顧問委任，通常約定 3–6 個月；專案完成或期滿即終止，不自動續約',
  },
  {
    id: 'CON-006',
    law: '依合約約定',
    name: '教育訓練合約服務期間',
    type: '合約期間',
    years: null,
    days: 90,
    display: '依課程安排',
    caseTypes: ['教育訓練'],
    note: '單次或系列課程委任合約，以課程完成為履行標準；通常附帶講義使用授權期間約定',
  },
]
